config/routes.rb
Workflo::Application.routes.draw do

  resources :projects do 
    resources :sections
    resources :members
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider/callback' => 'users/omniauth_callbacks#github'
    get '/users/auth/failure' => 'users/omniauth_callbacks#failure'
  end

  
  get '/account/edit' => 'account#edit', :as => :user_account_edit

  scope :format => true, :constraints => { :format => 'json' } do
    get '/users/list_json' => "users#index_with_json"
  end

  root :to => 'projects#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
	attr_accessible :user_id, :project_id, :role, :admin

	belongs_to :user
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :introduction, :pitch, :sub_title, :title, :user_id

  # Validations
  # Later.


  # Associations

  has_many :sections, :dependent => :destroy

  has_many :users, through: :members
  has_many :members, :dependent => :destroy

  belongs_to :user
  
  accepts_nested_attributes_for :sections


  # Actions

  after_create :add_creator_as_project_member
  after_create :add_initial_section


  def add_creator_as_project_member
    user_id = self.user_id
  	self.members.create(
  			user_id: user_id,
  			role: 'Co-Founder',
  			admin: true )
  end

  def add_initial_section
    self.sections.create(
      title: 'Planning',
      info: 'Planning is the most important stage!'
      )
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :info, :project_id, :title

  # Validations

  validates :title, presence: true, length: { minimum: 4, maximum: 100 }
  # validates :info, presence: false, length: { minimum: 140, maximum: 300 }

  # Associations

  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Default devise settings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:github]


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name

  # omniauth stuff 
  attr_accessible :github_uid

  # attr_accessible :title, :body
  has_many :projects, through: :members
  has_many :members

  has_many :projects

def self.create_from_omniauth(omniauth)
  User.new.tap do |user|
    user.github_uid = omniauth["uid"]
    user.name = omniauth["info"]["nickname"]
    user.email = omniauth["info"]["email"]
    user.password = Devise.friendly_token[0,20]
    user.save!
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

    def create
    @project = Project.find(params[:project_id])
    @member  = @project.members.new(params[:member])
    respond_to do |format|
      if @member.save
        format.js 
      else
        format.html { render action: "new" }
      end
    end     
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all
		
	end
	
	def new
		@project = Project.new		
	end
	
	def show
		@project  = Project.find(params[:id])
		@sections = @project.sections
		@members  = @project.members
	end

	def create
	  @project = Project.new(params[:project])
	  @project.user_id = current_user.id
          respond_to do |format|
            if @project.save
              @section = @project.sections.build
              @member  = @project.members.build
              format.js 
            else
              format.html { render action: "new" }
            end
          end
		
	end


end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def new
     # @project = Project.find(params[:project_id])    
  end

  def create
    @project = Project.find(params[:project_id])
    @section = @project.sections.new(params[:section])
    respond_to do |format|
      if @section.save
        format.js 
      else
        format.html { render action: "new" }
      end
    end     
  end

def destroy
  @project = Project.find(params[:project_id])
  @section = @project.sections.find(params[:id])
  @section.destroy
  respond_to do |format| 
    # format.html
    format.js 
  end
end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    omniauth = request.env["omniauth.auth"]
    @user = User.find_by_github_uid(omniauth["uid"]) || User.create_from_omniauth(omniauth)
    # Hook into your own authentication system!
    sign_in_and_redirect @user, :event => :authentication
    # This would normally be configured to return to the previous path 
    redirect root_path, :notice => "Welcome, #{@user.name}"  
  end

  # def facebook
  #   # You need to implement the method below in your model (e.g. app/models/user.rb)
  #   @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

  #   if @user.persisted?
  #     flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
  #     sign_in_and_redirect @user, :event => :authentication
  #   else
  #     session["devise.facebook_data"] = request.env["omniauth.auth"]
  #     redirect_to new_user_registration_url
  #   end
  # end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    # Or alternatively,
    # raise ActionController::RoutingError.new('Not Found')
  end

  def failure
    puts "error"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index_with_json
    @users = User.where("name like ?", "%#{params[:q]}%")
    respond_to do |format|
      format.html
      format.json { render :json => @users.map(&:attributes) }
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
	def get_user_role(project, user)
		Member.where(project_id: project.id, user_id: user.id).first.role
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workflo</title>
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:200,400,600,700,300' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Merriweather+Sans:400,700,800' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Noto+Serif:400,700,400italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
		  $(document).ready(function() {
		  $('#sidr-plugin').sidr();
		});
  </script>
</head>
<body>
	<%= yield :project_header %>
		<nav id="top" class="borderize-light whitescale">
		<div class="wrapper">
			<img src="/assets/logo.png" style="margin-top:14px;" >

			<ul class="usericon">
				<% unless user_signed_in? %>
					<a href="/users/auth/github">Log In</a>
				<% else %>
					<li><a id="sidr-plugin" href="#usermenu"><div class="tiny-profile-picture"></div></a></li>
			</ul>

<!-- <div id="sidr">
  <ul>
    <li><a href="#">List 1</a></li>
    <li class="active"><a href="#">List 2</a></li>
    <li><a href="#">List 3</a></li>
  </ul>
</div> -->
				<div class="usermenu">
					<ul class="personal-menu">
						<li><a href="#">Home</a></li>
						<li><a href="#">New Workflo</a></li>
						<li><a href="#">Settings</a></li>
						<li><a href="/users/auth/github">Log in</a></li>
					</ul>
				</div>
			<% end %>			
		</div>

		</nav>
<%= yield %>

</body>
</html>

app/views/members/_new_member_icon.html.erb
<li>
	<div class="single-member">
			<%= image_tag 'http://y14.io/images/me.png', class: 'member' %>
			<span class="member-name"><%= project_member.user.name %></span>
			<span class="member-role">
				<%= get_user_role(project, project_member.user) %>
			</span>				
	</div>
</li>

app/views/members/_new_member_pop.html.erb
<div>
   <%= form_for [@project, @member], :remote => true do |builder| %>
          <%= builder.text_field :user_id %>
          <%= builder.text_field :project_id %>
          <%= builder.text_field :role %>
          <%= builder.submit %>
   <% end %>  
</div>

app/views/members/create.js.erb
$(document).ready(function(){
  var new_member = "<%= escape_javascript(render :partial => 'new_member_icon', :locals => { :project_member => @member, :project => @project }) %>"
  $('ul#team-circle li:last').before(new_member);
	$('a#new-member-modal').colorbox({
	  html:"<b>asdf</b>",
	  transition:"none",
	  speed:800,
	  fadeOut:200,
	  width:450,
	  height:300,
	  fixed:true, 
	  className:'issue-modal'
	 });
});

app/views/members/new.html.erb
<div class="new-team">
  <ul>
	<li>
		<div>
			<img src="http://y14.io/images/me.png" class="member">
		</div>
	</li>
	<li>
		<div>
			<img src="http://y14.io/images/me.png" class="member">
		</div>
	</li>
	<li>
		<div>
			<%= link_to image_tag('new_member.png'), '#', id: 'new-member-modal' %>
		</div>
	</li>
</ul>

app/views/projects/_new_modules.html.erb
<a name="new-modules" id="new-modules">
  <div class="fullwidth whitescale hidden">
    <div class="wrapper top-padding">
      <br /	>
      <img src="/assets/project_modules_ex.png" style="display:block; margin:0 auto;">
      <br><br>
      <div class="title-wrapper">
        <h2>Setting up modules</h2>
        <h6>Every project has its stages. What are yours?</h6>
      </div>


      <div class="new-modules">
        <ul class="module-circle">
  
        <% @project.sections.each do |project_section| %>
        <% unless project_section.title.nil? %>
          <%= render partial: 'sections/new_module_icon', locals: { section: project_section, project: @project } %>
          <% end %>
        <% end %>


<a href="#" id="new-module-modal">
  <li id="create-module"> 
            <%= image_tag('toolbox-turq.png') %>
            <%= link_to 'New Module', '#', id: 'new-module-modal', class: 'new-module-title create' %>
          </li></a>
  </ul>

        
        <br><br><br><br><br><br><br><br><br>
        <input type="submit" id="goto-team" data-destination="#new-team" class="btn" value="Next" />	

app/views/projects/_new_team.html.erb
<script type="text/javascript">

  $(document).ready(function(){

      var new_module_modal = "<%= escape_javascript(render(:partial => 'members/new_member_pop')) %>"

      $('a#new-member-modal').colorbox({
html:new_module_modal,
transition:"none",
speed:800,
fadeOut:200,
width:450,
height:300,
fixed:true, 
className:'issue-modal'
});
      });
    </script>



    <a name="new-team" id="new-team">
      <div class="fullwidth grayscale newform">
        <div class="wrapper top-padding">
          <br /	>
          <figure>
          <img src="/assets/celtics.jpg" >
          <figcaption>Boston Celtics 1965/6 team</figcaption>
          </figure>
          <br><br>
          <div class="title-wrapper">
            <h2>Great project means great team</h2>
            <h6>Or perhaps you were running solo?</h6>
          </div>

          <div class="new-team">
            <ul id="team-circle">
              <% @project.members.each do |project_member| %>
                <% unless project_member.user.nil? %>
                  <%= render :partial => 'members/new_member_icon', :locals => { :project_member => project_member, :project => @project } %>
                <% end %>
              <% end %>
              <li>
              <div class="single-member">
                <%= form_for [@project, @member], :remote => true do |builder| %>
                  <script type="text/javascript">

                    $(document).ready(function(){

                        $('#member_user_id').tokenInput('/users/list_json.json', {
crossDomain: false,
theme: "facebook"
                          });

                        $('.member-name-label').click(function(e){
                          e.preventDefault();
                          $(this).hide();
                          // $(this).before('<%= j builder.text_field :user_id %>');
                
                          });
                        });
                      </script>
                      <%= link_to image_tag('new_member.png'), '#', id: 'new-member-modal' %>
                      <span class="member-name-label">Name..</span>
                      <span class="member-role-label">Role..</span>				
                      <%= builder.text_field :user_id %>
                      <br />
                      <%= builder.submit %>
                    <% end %>
                  </div>	
                  </li>

                </ul>
                <br /> <br />
                <div class="center-btn">
                  <%= button_to 'Continue', project_path(@project), class: 'btn center-btn bright', method: :get %>
                </div>
              </div>
            </div>

app/views/projects/create.js.erb
$(document).ready(function(){

  $('#new-module-link').click(function(){
    e.preventDefault();
    alert('Hello');
  });


  function scrollNext(step){
    var $root = $('html, body');
    var destination = $(step).data('destination');
    $root.animate({
      scrollTop: $(destination).offset().top
    }, 500, function () {
      window.location.hash = destination;
    });
    return false;
  }

  $('#new-workflo').attr('disabled', 'disabled');
  
  /* First Stage */ 
  var new_modules = "<%= escape_javascript(render(:partial => 'new_modules')) %>";
  $("#container").append(new_modules);
  $('.fullwidth').height($(window).height());
  scrollNext('#new-workflo'); 

  // /* Second Stage */
  var new_team = "<%= escape_javascript(render(:partial => 'new_team')) %>";
  $('#goto-team').click(function(){
    $('#container').append(new_team);
    $('.fullwidth').height($(window).height());
    scrollNext('#goto-team');
    $('#goto-team').off();
  }); 


  var new_module_modal = "<%= escape_javascript(render(:partial => 'sections/new_module_pop')) %>"
    
 $('a#new-module-modal').colorbox({
	html:new_module_modal,
	transition:"none",
	speed:800,
	fadeOut:200,
	width:450,
	height:300,
	fixed:true,	
	className:'issue-modal'
 });

var edit_module_modal = "<%= escape_javascript(render(:partial => 'sections/edit_module_pop')) %>"

$('a#edit-module-modal').colorbox({
  html:edit_module_modal,
  transition:"none",
  speed:800,
  fadeOut:200,
  width:450,
  height:300,
  fixed:true, 
  className:'issue-modal'
 });




  /* Scroll */


}); 

app/views/sections/_edit_module_pop.html.erb
<div class="modal-wrapper center">
  <div class="new-module-wrapper">
    <%= form_for [@project, @section], :remote => true do |builder| %>
    <img src="/assets/toolbox-turq.png"><Br />
    <span id="name" class="label-input center-btn">Module Name..</span><br />
    <span id="info" class="label-input">Some explanation..</span>
    <%= builder.submit "Add", :id => 'submit-section' %>
   <% end %>  
  </div>
</div>

app/views/sections/_new_module_icon.html.erb
<li id="section-<%= section.id %>">
  <img src="/assets/toolbox-turq.png">
  <div class="new-module-title"><%= section.title %> </div>
  <%= button_to 'X', project_section_path(project, section), :confirm => "are you sure?", :remote => true, :method => :delete %>
</li>

app/views/sections/_new_module_pop.html.erb
<div class="modal-wrapper center">
  <div class="new-module-wrapper">

    <%= form_for [@project, @section], :remote => true do |builder| %>
<script type="text/javascript">
  $(document).ready(function(){
      $('#name').click(function(){
          $(this).hide();
          $(this).before('<%= j builder.text_field :title %>');
          });
 $('#info').click(function(){
          $(this).hide();
          $(this).before('<%= j builder.text_field :info %>');
        });
      });
</script>
    <img src="/assets/toolbox-turq.png"><Br />
    <span id="name" class="label-input center-btn">Module Name..</span><br />
    <span id="info" class="label-input">Some explanation..</span>
    <%= builder.submit "Add", :id => 'submit-section' %>
   <% end %>  
  </div>
</div>

app/views/sections/create.js.erb
$(document).ready(function(){
  var new_module = "<%= escape_javascript(render :partial => 'new_module_icon', :locals => { :section => @section, :project => @project }) %>"
  $('ul.module-circle li:last').before(new_module);
        parent.jQuery.colorbox.close();        

  $('a#new-member-modal').colorbox({
  html:"<b>asdf</b>",
  transition:"none",
  speed:800,
  fadeOut:200,
  width:450,
  height:300,
  fixed:true, 
  className:'issue-modal'
 });

});

app/views/sections/destroy.js.erb
$(document).ready(function(){
	var current	= <%= @section.id %>;
	// $("ul.module-circle").find("[data-section_id='" + current + "']");
	$('li#section-<%= @section.id %>').remove();
});